version: "3.8"
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/atria/development/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room
      MYSQL_ROOT_PASSWORD: Hjx123456.
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/atria/development/redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
