enum EnvVariableEnum {
  REDIS_SERVER_HOST = "REDIS_SERVER_HOST",
  REDIS_SERVER_PROT = "REDIS_SERVER_PROT",
  REDIS_SERVER_DB = "REDIS_SERVER_DB",
  JWT_SECRET = "JWT_SECRET",
  JWT_ACCESS_TOKEN_EXPIRES = "JWT_ACCESS_TOKEN_EXPIRES",
  JWT_REFRESH_TOKEN_EXPIRES = "JWT_REFRESH_TOKEN_EXPIRES"
}

export default EnvVariableEnum;
