enum EnvVariableEnum {
  REDIS_SERVER_HOST = "REDIS_SERVER_HOST",
  REDIS_SERVER_PROT = "REDIS_SERVER_PROT",
  REDIS_SERVER_DB = "REDIS_SERVER_DB",
  JWT_SECRET = "JWT_SECRET",
  JWT_ACCESS_TOKEN_EXPIRES = "JWT_ACCESS_TOKEN_EXPIRES",
  JWT_REFRESH_TOKEN_EXPIRES = "JWT_REFRESH_TOKEN_EXPIRES",
  ALIYUN_ACCESS_KEY_ID = "ALIYUN_ACCESS_KEY_ID",
  ALIYUN_ACCESS_KEY_SECRET = "ALIYUN_ACCESS_KEY_SECRET"
}

export default EnvVariableEnum;
